---
properties:
  credentials:
    dashboarding:
      admin:
        password:
          $metadata:
            message: Enter password for Dashboarding admin user
            description: >
              This password should not be changed after initial deployment.
            type: password
            value: ${{cpc.GeneratePassword()}}
            storage_type: local
            storage_path: dashboarding_admin_password