---
properties:
  credentials:
    serviceaccount:
      kubeconfig:
        $metadata:
          type: text
          storage_type: state-branch
          auto_generate: false
          message: "Enter the service account (robot) user kubeconfig file content:"
          description: The kubeconfig file content from Gardener (Can be found in MEMBERS, section Service Accounts). You can use existing or add new.
