#!/usr/bin/env python3

import sys

from python_path import PythonPath

with PythonPath("../..", relative_to=__file__):
    from lib.gardener import gardener
kubeconfig = "./robot-kubeconfig.yml"
namespace = "garden-perftests"
shoot_name = "monika-vm"
template_file = "./shoot-template.yml"

# Create an instance of GardenerHelper.
# gardener = gardener.GardenerHelper(kubeconfig, namespace, shoot_name)

from landscape_tools import console_colors


def main():
    print(sys.argv)


if __name__ == "__main__":
    main()
