#!/usr/bin/env python3

import os
from pprint import pprint

import landscape_tools
import yaml
from python_path import PythonPath

with PythonPath("../../../", relative_to=__file__):
    from library.python.lib import common, config, gardener, lscrypt


def main():
    # resolve required params
    config_object = config.Config()
    with landscape_tools.color_output("green"):
        print("Resolved all configs")
    config_object.write_kubeconfig_file()
    gardener_helper = config_object.get_gardener_helper()
    config_object.print_config()
    if gardener_helper.shoot_exists():
        with landscape_tools.color_output("green"):
            print("Shoot already exists, will check if config exists in lscrypt")
            if lscrypt.read_yaml_file("cluster", "export.yml") is not None:
                print("Config already exists in lscrypt")
            else:
                with landscape_tools.color_output("green"):
                    print("Exporting shoot details")
                name = config_object.cluster_name
                namespace = config_object.namespace
                domain = config_object.get_dns_domain()
                kubeconfig = gardener_helper.get_kubeconfig()
                # we create a dict and convert that to yaml
                export = {
                    "exports": {
                        "clusters": [
                            {
                                "name": name,
                                "namespace": namespace,
                                "domain": domain,
                                "kubeconfig": kubeconfig,
                            }
                        ]
                    }
                }
                lscrypt.write("cluster", "export.yml", export)
    else:
        with landscape_tools.color_output("green"):
            print(f"Creating shoot with name {config_object.cluster_name}")
        gardener_helper.create_shoot(config_object.rendered_shoot_path)
        creation_status = gardener_helper.poll_shoot_status(timeout=3000, interval=10)
        if creation_status is True:
            name = config_object.cluster_name
            namespace = config_object.gardener_namespace
            domain = config_object.get_dns_domain()
            kubeconfig = gardener_helper.get_kubeconfig()
            # we create a dict and convert that to yaml
            export = {
                "exports": {
                    "clusters": [
                        {
                            "name": name,
                            "namespace": namespace,
                            "domain": domain,
                            "kubeconfig": kubeconfig,
                        }
                    ]
                }
            }
            lscrypt.write("cluster", "export.yml", export)
            with landscape_tools.color_output("green"):
                print("Exported shoot details")
        else:
            with landscape_tools.color_output("red"):
                print("Shoot creation failed")
            exit(1)


if __name__ == "__main__":
    main()
