#!/usr/bin/env python3

import os
from pprint import pprint

import landscape_tools
import yaml
from python_path import PythonPath

with PythonPath("../../../", relative_to=__file__):
    from library.python.lib import common, gardener, lscrypt, config


def main():
    # resolve required params
    config_object = config.Config()
    config_object.write_kubeconfig_file()
    gardener_helper = config_object.get_gardener_helper()
    config_object.print_config()
    gardener_helper.delete_shoot(config_object.rendered_shoot_path)
    creation_status = gardener_helper.poll_shoot_status(timeout=300, interval=10)
    with landscape_tools.color_output("green"):
        print(creation_status)


if __name__ == "__main__":
    main()
